### ISSUE TITLE
[Question] session-file-store errors in server logs

### ISSUE THREAD

**Issue by akvelon-georgii-ivanov** [os-js/osjs-server#2]
Error: EPERM: operation not permitted, rename 'USER\PATH\TO\OS.js\sessions\Nnm-q0myVZReDkZC42zWuqf6CVYBlWhI.json.3995843885' -> 'USER\PATH\TO\OS.js\sessions\Nnm-q0myVZReDk
ZC42zWuqf6CVYBlWhI.json'

Hi, @andersevenrud .

I'm not sure that is your code issue but session (as I saw you use `express-session` package) can't properly rename session file and read it normally on Windows.

I found this issues:
https://github.com/valery-barysok/session-file-store/issues/58
https://github.com/valery-barysok/session-file-store/issues/51

According to those issues I just need run app as admin. But I don't know why because `sessions` folder is in current user home directory.

I see there a few solutions for improvements:

- Run your OS.js and request for admin privileges for the process;
- Update documentation and put there a requirement run app as admin;
- Open an issue to `session-file-store` GitHub and wait for a response.
- Use `connect-loki` instead `session-file-store` as I see in issue 58 there is not such problem: https://www.npmjs.com/package/connect-loki

Thanks.

**Comment by andersevenrud** [comment]
> Open an issue to session-file-store GitHub and wait for a response.

There are already open issues on this in their repo(s).

> Run your OS.js and request for admin privilege for the process;

The OS.js server should not require any administration privileges, and running a HTTP server as root/admin is a very bad idea. Also messing with permissions is not recommended.

> According to those issues I just need run app as admin.

This won't solve the problem. The issue here is how the session file store handles the actual files. It will fail in *some* cases (intermittent) and then spit out an error log, which really is more like a warning as it all works fine (it retries until it succeeds).

So, there's not much I can do about this sadly. I even get this on my development box... but not private server.

**Comment by akvelon-georgii-ivanov** [comment]
> There are already open issues on this in their repo(s).
They closed those issues because it fixed for win7, as I see. But not for win10 (see the last comments @ 58).

**Comment by andersevenrud** [comment]
This is the open issue: https://github.com/valery-barysok/session-file-store/issues/41

**Comment by akvelon-georgii-ivanov** [comment]
Okay. Will wait for a solution here.
I tested stored JSON files. It looks correct but this message is just annoying...

**Comment by andersevenrud** [comment]
I'll look into using connect-loki. It depends on how much more extra dependencies etc. that will produce.

**Comment by andersevenrud** [comment]
I've done some testing with `connect-loki` and it works like a charm. I just made a commit using this, so it will be in the next release :)

**Comment by andersevenrud** [comment]
New release is out, and problem fixed (even with persistent storage). Thanks, man! :+1:
